name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Build
      run: |
        go install github.com/icexin/eggos/cmd/egg@latest
        alias go1.16.13=go
        make primes.iso

    - name: Test
      run: go test -v ./...

    - name: gosec
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@latest
        gosec .

    - name: golangci-lint
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.43.0
        golangci-lint run --skip-files='.*_test.go' --disable=errcheck

    - name: gokart
      run: |
        go install github.com/praetorian-inc/gokart@latest
        gokart scan

    - uses: actions/upload-artifact@v2
      with:
        name: primes
        path: primes.iso

    - name: Version correctly
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cp primes.iso primes-${GITHUB_REF#refs/*/}.iso

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          primes-${GITHUB_REF#refs/*/}.iso
